# 1. Import Libraries

In [16]:
import pandas as pd
import numpy as np

import re
import string

import os

# 2. Load Raw Dataset

In [17]:
fake_path = "../data/raw/fake.csv"
true_path = "../data/raw/true.csv"


fake_df = pd.read_csv(fake_path)
true_df = pd.read_csv(true_path)

# adding labels to the datasets
fake_df["label"] = 0
true_df["label"] = 1

# combining the datasets and shuffling the rows
df = pd.concat(
    [fake_df, true_df],
    axis=0
)

df = df.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

In [18]:
df

,title,text,subject,date,label
0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",0
1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",1
2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",1
3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",0
4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",1
...,...,...,...,...,...
44893,UNREAL! CBS’S TED KOPPEL Tells Sean Hannity He...,,politics,"Mar 27, 2017",0
44894,PM May seeks to ease Japan's Brexit fears duri...,LONDON/TOKYO (Reuters) - British Prime Ministe...,worldnews,"August 29, 2017",1
44895,Merkel: Difficult German coalition talks can r...,BERLIN (Reuters) - Chancellor Angela Merkel sa...,worldnews,"November 16, 2017",1
44896,Trump Stole An Idea From North Korean Propaga...,Jesus f*cking Christ our President* is a moron...,News,"July 14, 2017",0
44897,BREAKING: HILLARY CLINTON’S STATE DEPARTMENT G...,IF SHE S NOT TOAST NOW THEN WE RE IN BIGGER TR...,politics,"Apr 23, 2015",0

# 3. Handle Missing Values & Duplicates

In [19]:
# Checking for null values and dropping them
df.isnull().sum()
df = df.dropna()

In [20]:
# Checking for duplicate rows and dropping them
df.duplicated().sum()
df = df.drop_duplicates()

# 4. Clean text

In [21]:
df["content"] = (
    df["title"]
    + " "
    + df["text"]
)

df.head()

,title,text,subject,date,label,content
0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",0,Ben Stein Calls Out 9th Circuit Court: Committ...
1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",1,Trump drops Steve Bannon from National Securit...
2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",1,Puerto Rico expects U.S. to lift Jones Act shi...
3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",0,OOPS: Trump Just Accidentally Confirmed He Le...
4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",1,Donald Trump heads for Scotland to reopen a go...

In [22]:
# Cleaning the text data
def clean_text(text):

    text = text.lower()

    # remove urls
    text = re.sub(
        r"http\S+|www\S+",
        "",
        text
    )

    # remove html
    text = re.sub(
        r"<.*?>",
        "",
        text
    )

    # remove punctuation
    text = text.translate(
        str.maketrans(
            "",
            "",
            string.punctuation
        )
    )

    # remove extra spaces
    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text

In [23]:
df["clean_text"] = df["content"].apply(clean_text)

# 5. Save Processed Dataset

In [24]:
output_path = "../data/processed/cleaned_news.csv"

df.to_csv(
    output_path,
    index=False
)